name: Build Binaries for Mac

on:
  push:
    tags:
      - '*canary*'

jobs:
  publish:
    name: Build Binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11
            artifact_name: carpe
            dir: dmg
            asset_name: carpe-macos-11
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - uses: actions/checkout@v1

      - name: set the Mac compile target
        if: matrix.os == 'macos-11'
        run: export CARGO_BUILD_TARGET='universal-apple-darwin'

      - name: yarn installation
        run: yarn install
      - name: Build Tauri
        run: RUST_BACKTRACE=1 yarn run tauri build
      - name: Rename binary
        run: mv src-tauri/target/release/bundle/${{ matrix.dir }}/*.${{ matrix.dir}} src-tauri/target/release/bundle/${{ matrix.dir }}/${{matrix.asset_name}}.${{matrix.dir}}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: ${{matrix.asset_name}}
          file: src-tauri/target/release/bundle/${{ matrix.dir }}/*.${{ matrix.dir}}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Upload Updater Builds
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: updater-${{matrix.asset_name}}
          file: src-tauri/target/release/bundle/macos/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
